### ISSUE TITLE
unordered list tag css goes wrong

### ISSUE THREAD

**Issue by saigontech** [saigontech/sgt-wiki-base#4]
<img width="918" alt="Screen Shot 2021-10-02 at 13 48 13" src="https://user-images.githubusercontent.com/43031698/135703954-87dba7e0-dcf0-4fac-bccd-c802961cea3e.png">

**Comment by hdkhoasgt** [comment]
@saigontech 
Can not reproduct this issue

**Comment by huynq2007** [comment]
sorry, it has been fixed somehow!
